### PR TITLE
TF2 bundle

### PR DESCRIPTION
**Pull request by ahiguera-mx**
Add the option to use saved model "bundle" from TF in `CVNEvaluator_module.cc`
Context: Our model was trained with TF2.11, and `dunesw` relies on a `protobuf` format for the model, which is a legacy format from TF1.x. Unfortunately, our model couldn't be directly translated into that format, hence this implementation 
In addition, TensorFlow 2.x encourages the use of the SavedModel format for saving and loading models. SavedModel is a comprehensive, language-neutral, recoverable serialization format, which encapsulates the complete TensorFlow program, including weights. 

This PR has been tested against `dunereco v09_81_00d02`

### CODE REVIEW

**Comment by absolution1** [comment]
Hi @ahiguera-mx 
Thank you for these.  

It looks like the weight files are currently on /exp/data/dune?
We'll need to get those moved to stash cache
The beam files are stored as follows:
`"cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/CVN/beam/v03_00_00/dune_cvn_hd_2x6_nu_2023_tf26_v03_00_00.pb"`

So we could store the atmos files as
`"cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/CVN/atmos/v04_00_00/dune_cvn_hd_2x6_atmos_2024_tf21_v04_00_00.pb"`

@ahiguera-mx is the TF version correct in the file path that I've listed?

@tomjunk would you be able to help with stash cache deployment?

@AndyChappell will connect up the producer with the atmos fcl in dunesw.

**Comment by ahiguera-mx** [comment]
> Hi @ahiguera-mx Thank you for these.
> 
> It looks like the weight files are currently on /exp/data/dune? We'll need to get those moved to stash cache The beam files are stored as follows: `"cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/CVN/beam/v03_00_00/dune_cvn_hd_2x6_nu_2023_tf26_v03_00_00.pb"`

Yes, currently they are on `/exp/data/dune/` and is the saved model "bundle" directory so it is not a .pb file, that is the whole point of this PR, being able to use the bundle, regarding naming convention  I gues should be `dune_cvn_hd_2x6x1_nu_2024_tf211_v01_00_00` 

So technically we just need to rename the top directory `ResNet_20240204` --> `dune_cvn_hd_2x6x1_nu_2024_tf211_v01_00_00` 

> So we could store the atmos files as `"cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/CVN/atmos/v04_00_00/dune_cvn_hd_2x6_atmos_2024_tf21_v04_00_00.pb"`
Yes
> @ahiguera-mx is the TF version correct in the file path that I've listed?
We use, TF 2.11, need to correct taht 
> @tomjunk would you be able to help with stash cache deployment?
> 
> @AndyChappell will connect up the producer with the atmos fcl in dunesw.

**Comment by absolution1** [comment]
So then:

all of the files stored in: `/exp/dune/data/users/higuera/CNN/atmo_model_tf_2_11/ResNet_20240204/`

should move to `/cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/CVN/atmos/v04_00_00/dune_cvn_hd_1x2x6_nu_2024_tf211_v04_00_00`

**Comment by ahiguera-mx** [comment]
Yes all the files stored in ResNet_20240204On Feb 29, 2024, at 3:41 AM, Dom Brailsford ***@***.***> wrote:﻿
So then:
all of the files stored in: /exp/dune/data/users/higuera/CNN/atmo_model_tf_2_11/ResNet_20240204/
should move to /cvmfs/dune.osgstorage.org/pnfs/fnal.gov/usr/dune/persistent/stash/CVN/atmos/v04_00_00/dune_cvn_hd_1x2x6_nu_2024_tf211_v04_00_00

**Comment by tomjunk** [comment]
Files deployed in StashCache -- should show up in CVMFS soon.

**Comment by absolution1** [comment]
Thanks @tomjunk 

@ahiguera-mx please update the file path in the PR and check that its still readable in a job.  Once confirmed we can approve the PR :)

**Comment by ahiguera-mx** [comment]
@absolution1 I have updated the path to the model boundle

**Review by absolution1 — APPROVED** [review]
Great, thank you @ahiguera-mx

**Pull request merged**
